//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ((((()(()(((((((()))(((()((((()())(())()(((()((((((()((()(()(((()(()((())))()((()()())))))))))()((((((())((()))(((((()(((((((((()()))((()(())()((())((()(()))((()))()))()(((((()(((()()))()())((()((((())()())()((((())()(()(()(((()(())(()(())(((((((())()()(((())(()(()(()(())))(()((((())((()))(((()(()()(((((()()(()(((()(((((())()))()((()(()))()((()((((())((((())(()(((())()()(()()()()()(())((((())((())(()()))()((((())))((((()())()((((())((()())((())(())(((((()((((()(((()((((())(()(((()()))()))((((((()((())()())) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay1 {
            get {
                return ResourceManager.GetString("InputDay1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1321131112.
        /// </summary>
        internal static string InputDay10 {
            get {
                return ResourceManager.GetString("InputDay10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hxbxwxba.
        /// </summary>
        internal static string InputDay11 {
            get {
                return ResourceManager.GetString("InputDay11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;a&quot;:{&quot;e&quot;:{&quot;e&quot;:161,&quot;a&quot;:&quot;blue&quot;,&quot;d&quot;:{&quot;e&quot;:-14,&quot;a&quot;:&quot;red&quot;,&quot;d&quot;:{&quot;c&quot;:&quot;yellow&quot;,&quot;a&quot;:[-35,0],&quot;b&quot;:&quot;orange&quot;,&quot;d&quot;:{&quot;e&quot;:70,&quot;a&quot;:&quot;green&quot;,&quot;d&quot;:&quot;blue&quot;,&quot;j&quot;:12,&quot;c&quot;:69,&quot;h&quot;:&quot;orange&quot;,&quot;b&quot;:92,&quot;g&quot;:&quot;yellow&quot;,&quot;f&quot;:&quot;green&quot;,&quot;i&quot;:121}},&quot;c&quot;:&quot;blue&quot;,&quot;h&quot;:14,&quot;b&quot;:46,&quot;g&quot;:62,&quot;f&quot;:[179]},&quot;j&quot;:{&quot;e&quot;:133,&quot;c&quot;:&quot;violet&quot;,&quot;a&quot;:&quot;orange&quot;,&quot;b&quot;:&quot;blue&quot;,&quot;d&quot;:&quot;violet&quot;},&quot;c&quot;:{&quot;e&quot;:151,&quot;a&quot;:&quot;violet&quot;,&quot;d&quot;:{&quot;e&quot;:&quot;red&quot;,&quot;c&quot;:93,&quot;a&quot;:135,&quot;g&quot;:{&quot;e&quot;:43,&quot;c&quot;:&quot;green&quot;,&quot;a&quot;:&quot;orange&quot;,....
        /// </summary>
        internal static string InputDay12 {
            get {
                return ResourceManager.GetString("InputDay12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alice would gain 54 happiness units by sitting next to Bob.
        ///Alice would lose 81 happiness units by sitting next to Carol.
        ///Alice would lose 42 happiness units by sitting next to David.
        ///Alice would gain 89 happiness units by sitting next to Eric.
        ///Alice would lose 89 happiness units by sitting next to Frank.
        ///Alice would gain 97 happiness units by sitting next to George.
        ///Alice would lose 94 happiness units by sitting next to Mallory.
        ///Bob would gain 3 happiness units by sitting next to Alice.
        ///Bob would l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay13 {
            get {
                return ResourceManager.GetString("InputDay13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay14 {
            get {
                return ResourceManager.GetString("InputDay14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay15 {
            get {
                return ResourceManager.GetString("InputDay15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay16 {
            get {
                return ResourceManager.GetString("InputDay16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay17 {
            get {
                return ResourceManager.GetString("InputDay17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay18 {
            get {
                return ResourceManager.GetString("InputDay18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay19 {
            get {
                return ResourceManager.GetString("InputDay19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x23x21
        ///22x29x19
        ///11x4x11
        ///8x10x5
        ///24x18x16
        ///11x25x22
        ///2x13x20
        ///24x15x14
        ///14x22x2
        ///30x7x3
        ///30x22x25
        ///29x9x9
        ///29x29x26
        ///14x3x16
        ///1x10x26
        ///29x2x30
        ///30x10x25
        ///10x26x20
        ///1x2x18
        ///25x18x5
        ///21x3x24
        ///2x5x7
        ///22x11x21
        ///11x8x8
        ///16x18x2
        ///13x3x8
        ///1x16x19
        ///19x16x12
        ///21x15x1
        ///29x9x4
        ///27x10x8
        ///2x7x27
        ///2x20x23
        ///24x11x5
        ///2x8x27
        ///10x28x10
        ///24x11x10
        ///19x2x12
        ///27x5x10
        ///1x14x25
        ///5x14x30
        ///15x26x12
        ///23x20x22
        ///5x12x1
        ///9x26x9
        ///23x25x5
        ///28x16x19
        ///17x23x17
        ///2x27x20
        ///18x27x13
        ///16x7x18
        ///22x7x29
        ///17x28x6
        ///9x22x17
        ///10x5x6
        ///14x2x12
        ///25x5x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay2 {
            get {
                return ResourceManager.GetString("InputDay2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay20 {
            get {
                return ResourceManager.GetString("InputDay20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay21 {
            get {
                return ResourceManager.GetString("InputDay21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay22 {
            get {
                return ResourceManager.GetString("InputDay22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay23 {
            get {
                return ResourceManager.GetString("InputDay23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay24 {
            get {
                return ResourceManager.GetString("InputDay24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay25 {
            get {
                return ResourceManager.GetString("InputDay25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v&gt;v&lt;vvv&lt;&lt;vv^v&lt;v&gt;vv&gt;v&lt;&lt;&lt;^^^^^&lt;&lt;^&lt;vv&gt;^&gt;v^&gt;^&gt;^&gt;^&gt;^&gt;&lt;vvvv&lt;^&gt;^&lt;&lt;^&gt;&lt;&lt;&lt;^vvvv&gt;^&gt;^&gt;&lt;^v^&gt;&lt;^&lt;&gt;^^&gt;^vvv^&lt;vv&gt;&gt;^&gt;^^&lt;&gt;&gt;&lt;&gt;^&gt;vvv&gt;&gt;^vv&gt;^&lt;&gt;&lt;&gt;^&lt;v^&gt;^&gt;^&gt;&lt;vv^vv^&gt;&gt;&lt;&lt;^&gt;&lt;&lt;v&gt;&gt;&lt;&gt;^&lt;^&gt;&gt;vvv&gt;v&gt;&gt;&gt;v&lt;&lt;^&lt;&gt;&lt;^&lt;v&lt;&gt;v&gt;^^v^^^&lt;^v^^&gt;&gt;&gt;&lt;^&gt;^&gt;v&lt;&gt;^&lt;&gt;&gt;^&gt;^^v^&gt;&lt;v&lt;v&gt;&gt;&gt;&lt;&gt;v&lt;v^v&gt;^v&lt;&gt;&gt;^&gt;&lt;v&gt;^&lt;&gt;v^&gt;^&lt;&gt;^v^^^v^^&gt;&gt;vv&lt;&lt;^^&gt;&lt;^&lt;vvv&gt;^&gt;^^&lt;^&gt;&gt;^^^^^v^&lt;v&gt;vv&lt;&gt;&gt;v^v&lt;^v^^&lt;&gt;&lt;^&lt;^vv^&gt;&lt;&gt;&gt;&lt;&gt;&lt;&gt;v&gt;vvv^vv^^&lt;&lt;&gt;&lt;&lt;vvv&gt;&lt;&lt;^v^&gt;&lt;v&lt;&gt;vvv^&lt;^&gt;vvvv^&gt;^&gt;&gt;^v^&lt;v^vv&lt;^^v&lt;&gt;v&gt;vv^&lt;&gt;&gt;&lt;v&lt;&lt;&lt;^v^&lt;&lt;&gt;&lt;v&lt;^&lt;^&lt;&gt;&lt;^^^&gt;^&gt;&gt;v&gt;^&gt;v^&lt;&gt;v&gt;&lt;^&l....
        /// </summary>
        internal static string InputDay3 {
            get {
                return ResourceManager.GetString("InputDay3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ckczppom.
        /// </summary>
        internal static string InputDay4 {
            get {
                return ResourceManager.GetString("InputDay4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sszojmmrrkwuftyv
        ///isaljhemltsdzlum
        ///fujcyucsrxgatisb
        ///qiqqlmcgnhzparyg
        ///oijbmduquhfactbc
        ///jqzuvtggpdqcekgk
        ///zwqadogmpjmmxijf
        ///uilzxjythsqhwndh
        ///gtssqejjknzkkpvw
        ///wrggegukhhatygfi
        ///vhtcgqzerxonhsye
        ///tedlwzdjfppbmtdx
        ///iuvrelxiapllaxbg
        ///feybgiimfthtplui
        ///qxmmcnirvkzfrjwd
        ///vfarmltinsriqxpu
        ///oanqfyqirkraesfq
        ///xilodxfuxphuiiii
        ///yukhnchvjkfwcbiq
        ///bdaibcbzeuxqplop
        ///ivegnnpbiyxqsion
        ///ybahkbzpditgwdgt
        ///dmebdomwabxgtctu
        ///ibtvimgfaeonknoh
        ///jsqraroxudetmfyw
        ///dqdbcwtpintfcvuz
        ///tiyphjunlxddenpj
        ///fgqwjgntxagidhah
        ///nwenhxma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay5 {
            get {
                return ResourceManager.GetString("InputDay5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn on 887,9 through 959,629
        ///turn on 454,398 through 844,448
        ///turn off 539,243 through 559,965
        ///turn off 370,819 through 676,868
        ///turn off 145,40 through 370,997
        ///turn off 301,3 through 808,453
        ///turn on 351,678 through 951,908
        ///toggle 720,196 through 897,994
        ///toggle 831,394 through 904,860
        ///toggle 753,664 through 970,926
        ///turn off 150,300 through 213,740
        ///turn on 141,242 through 932,871
        ///toggle 294,259 through 474,326
        ///toggle 678,333 through 752,957
        ///toggle 393,804 through 510,976
        ///turn off 6,964 through  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay6 {
            get {
                return ResourceManager.GetString("InputDay6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af AND ah -&gt; ai
        ///NOT lk -&gt; ll
        ///hz RSHIFT 1 -&gt; is
        ///NOT go -&gt; gp
        ///du OR dt -&gt; dv
        ///x RSHIFT 5 -&gt; aa
        ///at OR az -&gt; ba
        ///eo LSHIFT 15 -&gt; es
        ///ci OR ct -&gt; cu
        ///b RSHIFT 5 -&gt; f
        ///fm OR fn -&gt; fo
        ///NOT ag -&gt; ah
        ///v OR w -&gt; x
        ///g AND i -&gt; j
        ///an LSHIFT 15 -&gt; ar
        ///1 AND cx -&gt; cy
        ///jq AND jw -&gt; jy
        ///iu RSHIFT 5 -&gt; ix
        ///gl AND gm -&gt; go
        ///NOT bw -&gt; bx
        ///jp RSHIFT 3 -&gt; jr
        ///hg AND hh -&gt; hj
        ///bv AND bx -&gt; by
        ///er OR es -&gt; et
        ///kl OR kr -&gt; ks
        ///et RSHIFT 1 -&gt; fm
        ///e AND f -&gt; h
        ///u LSHIFT 1 -&gt; ao
        ///he RSHIFT 1 -&gt; hx
        ///eg AND ei -&gt; ej
        ///bo AND bu -&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay7 {
            get {
                return ResourceManager.GetString("InputDay7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;sjdivfriyaaqa\xd2v\&quot;k\&quot;mpcu\&quot;yyu\&quot;en&quot;
        ///&quot;vcqc&quot;
        ///&quot;zbcwgmbpijcxu\&quot;yins\&quot;sfxn&quot;
        ///&quot;yumngprx&quot;
        ///&quot;bbdj&quot;
        ///&quot;czbggabkzo\&quot;wsnw\&quot;voklp\&quot;s&quot;
        ///&quot;acwt&quot;
        ///&quot;aqttwnsohbzian\&quot;evtllfxwkog\&quot;cunzw&quot;
        ///&quot;ugvsgfv&quot;
        ///&quot;xlnillibxg&quot;
        ///&quot;kexh\&quot;pmi&quot;
        ///&quot;syvugow&quot;
        ///&quot;m\&quot;ktqnw&quot;
        ///&quot;yrbajyndte\\rm&quot;
        ///&quot;f\&quot;kak\x70sn\xc4kjri&quot;
        ///&quot;yxthr&quot;
        ///&quot;alvumfsjni\&quot;kohg&quot;
        ///&quot;trajs\x5brom\xf1yoijaumkem\&quot;\&quot;tahlzs&quot;
        ///&quot;\&quot;oedr\&quot;pwdbnnrc&quot;
        ///&quot;qsmzhnx\&quot;&quot;
        ///&quot;\&quot;msoytqimx\\tbklqz&quot;
        ///&quot;mjdfcgwdshrehgs&quot;
        ///&quot;\&quot;rivyxahf\&quot;&quot;
        ///&quot;ciagc\x04bp&quot;
        ///&quot;xkfc&quot;
        ///&quot;xrgcripdu\x4c\xc4gszjhrvumvz\&quot;mngbirb&quot;
        ///&quot;gvmae\&quot;yiiu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay8 {
            get {
                return ResourceManager.GetString("InputDay8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tristram to AlphaCentauri = 34
        ///Tristram to Snowdin = 100
        ///Tristram to Tambi = 63
        ///Tristram to Faerun = 108
        ///Tristram to Norrath = 111
        ///Tristram to Straylight = 89
        ///Tristram to Arbre = 132
        ///AlphaCentauri to Snowdin = 4
        ///AlphaCentauri to Tambi = 79
        ///AlphaCentauri to Faerun = 44
        ///AlphaCentauri to Norrath = 147
        ///AlphaCentauri to Straylight = 133
        ///AlphaCentauri to Arbre = 74
        ///Snowdin to Tambi = 105
        ///Snowdin to Faerun = 95
        ///Snowdin to Norrath = 48
        ///Snowdin to Straylight = 88
        ///Snowdin to Arbre = 7
        ///Tambi to Faeru [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay9 {
            get {
                return ResourceManager.GetString("InputDay9", resourceCulture);
            }
        }
    }
}
