//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2016 {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2016.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L5, R1, L5, L1, R5, R1, R1, L4, L1, L3, R2, R4, L4, L1, L1, R2, R4, R3, L1, R4, L4, L5, L4, R4, L5, R1, R5, L2, R1, R3, L2, L4, L4, R1, L192, R5, R1, R4, L5, L4, R5, L1, L1, R48, R5, R5, L2, R4, R4, R1, R3, L1, L4, L5, R1, L4, L2, L5, R5, L2, R74, R4, L1, R188, R5, L4, L2, R5, R2, L4, R4, R3, R3, R2, R1, L3, L2, L5, L5, L2, L1, R1, R5, R4, L3, R5, L1, L3, R4, L1, L3, L2, R1, R3, R2, R5, L3, L1, L1, R5, L4, L5, R5, R2, L5, R2, L1, L5, L3, L5, L5, L1, R1, L4, L3, L1, R2, R5, L1, L3, R4, R5, L4, L1, R5, L1, R5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay01 {
            get {
                return ResourceManager.GetString("InputDay01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRRLLLRDRURUDLRDDURULRULLDLRRLRLDULUDDDDLLRRLDUUDULDRURRLDULRRULDLRDUDLRLLLULDUURRRRURURULURRULRURDLULURDRDURDRLRRUUDRULLLLLDRULDDLLRDLURRLDUURDLRLUDLDUDLURLRLDRLUDUULRRRUUULLRDURUDRUDRDRLLDLDDDLDLRRULDUUDULRUDDRLLURDDRLDDUDLLLLULRDDUDDUUULRULUULRLLDULUDLLLLURRLDLUDLDDLDRLRRDRDUDDDLLLLLRRLLRLUDLULLDLDDRRUDDRLRDDURRDULLLURLRDLRRLRDLDURLDDULLLDRRURDULUDUDLLLDDDLLRLDDDLLRRLLURUULULDDDUDULUUURRUUDLDULULDRDDLURURDLDLULDUDUDDDDD
        ///RUURUDRDUULRDDLRLLLULLDDUDRDURDLRUULLLLUDUDRRUDUULRRUUDDURDDDLLLLRRUURULULLUDDLRDUDU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay02 {
            get {
                return ResourceManager.GetString("InputDay02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   330  143  338
        ///  769  547   83
        ///  930  625  317
        ///  669  866  147
        ///   15  881  210
        ///  662   15   70
        ///  273  277  707
        ///   50  592  770
        ///  280  313  407
        ///  642  487  372
        ///   94  619  295
        ///  734  243  141
        ///  220  141  515
        ///  198  824  745
        ///  210  787  964
        ///  213  627  601
        ///  918    4  447
        ///  805  630  802
        ///  711  237  987
        ///  938  552  388
        ///  643  405  779
        ///  803  747  525
        ///  917  832  631
        ///  899  292  843
        ///   81  206  445
        ///  141  874  465
        ///  177  974   54
        ///  520  725  814
        ///  271  958  554
        ///  779  579  264
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay03 {
            get {
                return ResourceManager.GetString("InputDay03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vxupkizork-sgmtkzoi-pkrrehkgt-zxgototm-644[kotgr]
        ///mbiyqoxsm-pvygob-nocsqx-900[obmqs]
        ///veqtekmrk-ikk-hitpscqirx-334[nrtws]
        ///gvcskirmg-fyrrc-irkmriivmrk-932[rikmc]
        ///xmtjbzidx-xviyt-yzqzgjkhzio-187[yzfeu]
        ///bwx-amkzmb-kivlg-kwibqvo-lmaqov-798[bkmva]
        ///vcibutulxiom-ohmnuvfy-yaa-mylpcwym-890[iyaun]
        ///ajvyjprwp-lqxlxujcn-jwjuhbrb-251[muivb]
        ///szfyrqriuflj-avccpsvre-kirzezex-971[rezcf]
        ///kwvacumz-ozilm-akidmvomz-pcvb-uizsmbqvo-590[uslyz]
        ///ucynmlgxcb-afmamjyrc-jmegqrgaq-626[rybxt]
        ///oaxadrgx-pkq-abqdmfuaze-872[xtbnw]
        ///t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay04 {
            get {
                return ResourceManager.GetString("InputDay04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wtnhxymk.
        /// </summary>
        internal static string InputDay05 {
            get {
                return ResourceManager.GetString("InputDay05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bztzdacg
        ///xyjtwqap
        ///arsiwubu
        ///cjwvfwtp
        ///dpdymenf
        ///kbedgnri
        ///gsrrprxn
        ///ojdxafjb
        ///umujtcwg
        ///fcpqbkti
        ///hfhxzhdt
        ///oradqnqo
        ///pjfgpkgz
        ///fagrqjrn
        ///xjkujuks
        ///iisbsyvl
        ///narthccx
        ///sjbnbbxp
        ///ljaemgip
        ///sdlenzfu
        ///zhzlsmgw
        ///sbdndyku
        ///ekcktelc
        ///vxgoapax
        ///bhepszpx
        ///hozlfbdm
        ///fkjgygrj
        ///keutuund
        ///agzrwrzb
        ///mgcucvkn
        ///wiguuvtm
        ///bnyviixq
        ///ybsozbss
        ///cxaqckwv
        ///ulnksnjj
        ///dsrvvmbs
        ///azfnwcdk
        ///hwtwbilm
        ///lieglyxh
        ///vpqfjxcv
        ///sfwxiyqr
        ///hqifjldw
        ///icnsplkz
        ///oxnqizfs
        ///nzfwhwyu
        ///ygaoadfd
        ///dctauvvs
        ///zmtgvtxg
        ///wwzpvoym
        ///cwhcqxvu
        ///rmcvjkzu
        ///yh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay06 {
            get {
                return ResourceManager.GetString("InputDay06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rhamaeovmbheijj[hkwbkqzlcscwjkyjulk]ajsxfuemamuqcjccbc
        ///gdlrknrmexvaypu[crqappbbcaplkkzb]vhvkjyadjsryysvj[nbvypeadikilcwg]jwxlimrgakadpxu[dgoanojvdvwfabtt]yqsalmulblolkgsheo
        ///dqpthtgufgzjojuvzvm[eejdhpcqyiydwod]iingwezvcbtowwzc[uzlxaqenhgsebqskn]wcucfmnlarrvdceuxqc[dkwcsxeitcobaylhbvc]klxammurpqgmpsxsr
        ///gmmfbtpprishiujnpdi[wedykxqyntvrkfdzom]uidgvubnregvorgnhm
        ///txxplravpgztjqcw[txgmmtlhmqpmmwp]bmhfgpmafxqwtrpr[inntmjmgqothdzfqgxq]cvtwvembpvdmcvk
        ///gkxjhpayoyrrpcr[mwyoahlkqyhtznyzrm]mvmurvsrgjunjjepn[mkoumuoh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay07 {
            get {
                return ResourceManager.GetString("InputDay07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rect 1x1
        ///rotate row y=0 by 20
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 4
        ///rect 2x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 6
        ///rect 5x1
        ///rotate row y=0 by 2
        ///rect 1x3
        ///rotat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay08 {
            get {
                return ResourceManager.GetString("InputDay08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (121x14)(7x7)UOBCTWD(24x1)KBBJJRCFNOTNFFCKJOFGWJZT(12x6)(7x3)CKJUMES(47x12)(2x3)IY(4x12)JSFP(12x13)FDTYFDWLHWXE(5x11)XLPGL(2x7)EK(113x4)(7x2)LTVKCEC(75x4)(22x8)XBUQNQXMZPOAACRFZACRVP(2x2)HV(33x10)HTJYEBCTFDFRIXRIUBWJJXFDNGBIVATET(14x6)(8x10)IGIWGAFX(102x2)(34x6)(6x14)AEVIDQ(8x10)BSMUYCJH(3x9)CQH(2x8)RC(33x4)(19x3)CPFEVGBWGTXAVXRBGPB(3x7)UDY(10x6)VMWBUOTFKL(349x6)(5x6)GZJZB(70x1)(3x11)JEL(13x6)TAKTWPYEOKXNW(2x1)JH(7x12)JGYKSGB(15x14)BBWIZVLZCTAVPQZ(56x4)(7x8)DITERGP(19x11)QHUEFNLLGAPSGBUERXM(11x10)XNAJVEWBNK [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay09 {
            get {
                return ResourceManager.GetString("InputDay09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bot 135 gives low to bot 27 and high to bot 166
        ///bot 57 gives low to bot 4 and high to bot 186
        ///bot 115 gives low to output 2 and high to bot 80
        ///bot 44 gives low to bot 175 and high to bot 88
        ///bot 167 gives low to bot 42 and high to bot 168
        ///bot 18 gives low to bot 32 and high to bot 89
        ///bot 199 gives low to bot 75 and high to bot 40
        ///bot 129 gives low to bot 178 and high to bot 147
        ///bot 163 gives low to bot 49 and high to bot 160
        ///value 2 goes to bot 143
        ///bot 176 gives low to bot 139 and high to bot 117
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay10 {
            get {
                return ResourceManager.GetString("InputDay10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first floor contains a polonium generator, a thulium generator, a thulium-compatible microchip, a promethium generator, a ruthenium generator, a ruthenium-compatible microchip, a cobalt generator, and a cobalt-compatible microchip.
        ///The second floor contains a polonium-compatible microchip and a promethium-compatible microchip.
        ///The third floor contains nothing relevant.
        ///The fourth floor contains nothing relevant..
        /// </summary>
        internal static string InputDay11 {
            get {
                return ResourceManager.GetString("InputDay11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cpy 1 a
        ///cpy 1 b
        ///cpy 26 d
        ///jnz c 2
        ///jnz 1 5
        ///cpy 7 c
        ///inc d
        ///dec c
        ///jnz c -2
        ///cpy a c
        ///inc a
        ///dec b
        ///jnz b -2
        ///cpy c b
        ///dec d
        ///jnz d -6
        ///cpy 13 c
        ///cpy 14 d
        ///inc a
        ///dec d
        ///jnz d -2
        ///dec c
        ///jnz c -5.
        /// </summary>
        internal static string InputDay12 {
            get {
                return ResourceManager.GetString("InputDay12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1350.
        /// </summary>
        internal static string InputDay13 {
            get {
                return ResourceManager.GetString("InputDay13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ahsbgdzn.
        /// </summary>
        internal static string InputDay14 {
            get {
                return ResourceManager.GetString("InputDay14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc #1 has 13 positions; at time=0, it is at position 1.
        ///Disc #2 has 19 positions; at time=0, it is at position 10.
        ///Disc #3 has 3 positions; at time=0, it is at position 2.
        ///Disc #4 has 7 positions; at time=0, it is at position 1.
        ///Disc #5 has 5 positions; at time=0, it is at position 3.
        ///Disc #6 has 17 positions; at time=0, it is at position 5..
        /// </summary>
        internal static string InputDay15 {
            get {
                return ResourceManager.GetString("InputDay15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01000100010010111.
        /// </summary>
        internal static string InputDay16 {
            get {
                return ResourceManager.GetString("InputDay16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ioramepc.
        /// </summary>
        internal static string InputDay17 {
            get {
                return ResourceManager.GetString("InputDay17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .^^.^^^..^.^..^.^^.^^^^.^^.^^...^..^...^^^..^^...^..^^^^^^..^.^^^..^.^^^^.^^^.^...^^^.^^.^^^.^.^^.^..
        /// </summary>
        internal static string InputDay18 {
            get {
                return ResourceManager.GetString("InputDay18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3014387.
        /// </summary>
        internal static string InputDay19 {
            get {
                return ResourceManager.GetString("InputDay19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 420604416-480421096
        ///172102328-195230700
        ///613677102-639635955
        ///1689844284-1724152701
        ///3358865073-3365629764
        ///1333423844-1344930397
        ///2519115700-2535290065
        ///698684483-723211151
        ///979757052-1003200781
        ///4165068842-4190472815
        ///2020267004-2045214369
        ///2979897715-3004836346
        ///2110213890-2115506975
        ///2970017340-2973461626
        ///2236378365-2258142409
        ///3423992974-3426380317
        ///1462489107-1490036931
        ///2189940955-2198476022
        ///2417413696-2430182746
        ///3624276792-3633790184
        ///1005063612-1009015074
        ///1061038892-1061410454
        ///2276099915-2310 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay20 {
            get {
                return ResourceManager.GetString("InputDay20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay21 {
            get {
                return ResourceManager.GetString("InputDay21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay22 {
            get {
                return ResourceManager.GetString("InputDay22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay23 {
            get {
                return ResourceManager.GetString("InputDay23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay24 {
            get {
                return ResourceManager.GetString("InputDay24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay25 {
            get {
                return ResourceManager.GetString("InputDay25", resourceCulture);
            }
        }
    }
}
