//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2017 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2017.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18144568296689784866596347266193986531397687719431268499352125948651752796139671756185482545396318113437957491837321373218469774666839963164262237368442532611258528394646232336399175389564717779769121478414921519871598694757366898718874687867839962453379255165133597984713197596567795775557135893466532748728731246777118798142478551478542178178197647732671267431199473594798738351669989791659543322829419875971595946957876673951847511877175578719623877234576294147735948345664119468533352832958111378859984362132 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay01 {
            get {
                return ResourceManager.GetString("InputDay01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4168	3925	858	2203	440	185	2886	160	1811	4272	4333	2180	174	157	361	1555
        ///150	111	188	130	98	673	408	632	771	585	191	92	622	158	537	142
        ///5785	5174	1304	3369	3891	131	141	5781	5543	4919	478	6585	116	520	673	112
        ///5900	173	5711	236	2920	177	3585	4735	2135	2122	5209	265	5889	233	4639	5572
        ///861	511	907	138	981	168	889	986	980	471	107	130	596	744	251	123
        ///2196	188	1245	145	1669	2444	656	234	1852	610	503	2180	551	2241	643	175
        ///2051	1518	1744	233	2155	139	658	159	1178	821	167	546	126	974	136	1946
        ///161	1438	3317	499 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay02 {
            get {
                return ResourceManager.GetString("InputDay02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 312051.
        /// </summary>
        internal static string InputDay03 {
            get {
                return ResourceManager.GetString("InputDay03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oaoe rxeq vssdqtu xrk cjv yaoqp loo
        ///mveua dogbam szydvri hyzk lbega abzqw xwjn wniug kwbre
        ///npaoy uivpxwd oynpa rcdk uixpvdw
        ///yserir iikzcm ieuroca iuwcfov rvb giti crdpdcv mxpps
        ///spyuhgo lucasl ucllsa bymnjig yflbv nxitmlf
        ///xlxyhwz xla mpye fvjegwg fezlfrt inetrh vhg xpvstx ydhvq
        ///xgue cvtmh myg ontvvyw ygm oqzrdrw
        ///srdfsjf dli kccb kauk kauk apa doefc cdffkhh cdffkhh
        ///msizb elqiov lqn epamk onmnlst baawab ncafwaf jrataml iyzhy svycuec
        ///wdzqpcn dkgdumv wdzqpcn qxdmwib cjsigi bgcihgh fmua
        ///kpvbzf kpvbzf sv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay04 {
            get {
                return ResourceManager.GetString("InputDay04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///0
        ///2
        ///-1
        ///1
        ///-4
        ///-4
        ///-5
        ///-2
        ///-1
        ///-4
        ///-8
        ///-8
        ///-1
        ///-6
        ///-9
        ///-3
        ///-14
        ///-6
        ///2
        ///-15
        ///-9
        ///-5
        ///-9
        ///-14
        ///-4
        ///-3
        ///-23
        ///-24
        ///2
        ///-24
        ///-22
        ///-31
        ///-23
        ///-5
        ///1
        ///-35
        ///-11
        ///0
        ///-30
        ///-18
        ///-25
        ///-24
        ///2
        ///-35
        ///-33
        ///-29
        ///-2
        ///-27
        ///-44
        ///-19
        ///-19
        ///-40
        ///-52
        ///-26
        ///-20
        ///-37
        ///1
        ///-40
        ///-36
        ///-29
        ///-37
        ///-56
        ///-59
        ///-34
        ///-31
        ///-17
        ///-24
        ///-14
        ///-57
        ///-16
        ///-68
        ///-27
        ///-60
        ///-73
        ///-16
        ///-60
        ///-6
        ///-45
        ///-38
        ///-48
        ///-33
        ///-68
        ///-12
        ///-51
        ///-49
        ///-10
        ///-28
        ///-66
        ///-88
        ///-8
        ///-83
        ///-5
        ///-2
        ///-39
        ///-39
        ///-12
        ///-87
        ///-63
        ///-55
        ///-55
        ///-26
        ///-5
        ///1
        ///-68
        ///-100
        ///-98
        ///-71
        ///-15
        ///-96
        ///-100
        ///-10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay05 {
            get {
                return ResourceManager.GetString("InputDay05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0	5	10	0	11	14	13	4	11	8	8	7	1	4	12	11.
        /// </summary>
        internal static string InputDay06 {
            get {
                return ResourceManager.GetString("InputDay06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmqyju (156) -&gt; rjzvwv, noybkx
        ///dvkug (90) -&gt; tbjbz, gxnvl
        ///meeiw (95)
        ///iaibv (52)
        ///ckddz (36)
        ///yikfhvr (52)
        ///phqiqi (92)
        ///ywctcn (38)
        ///boofr (332) -&gt; aqiun, zilgfzu
        ///zfusug (65)
        ///yffcj (90) -&gt; bbmmtud, bqbgocl, kgntkz, mmfwbku, asefoiu
        ///velbwcl (432)
        ///liori (107) -&gt; fzcts, wgfbd
        ///watknc (96)
        ///wbpvo (77) -&gt; dtdkt, ixhnyqi
        ///mladbjo (27)
        ///cimsvsq (69)
        ///ugyjqg (10)
        ///tmybiz (55)
        ///ueheft (12)
        ///awweagx (26)
        ///zxiqpq (88)
        ///atcrb (92)
        ///ocauj (95)
        ///ayqfub (306) -&gt; drwyz, prssjgo
        ///xbeau (76) -&gt; xxshfpr, renhdd
        ///tmicb  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay07 {
            get {
                return ResourceManager.GetString("InputDay07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y inc 497 if n &lt;= 3
        ///ig inc -54 if es &lt; 9
        ///j dec 278 if low &lt; 10
        ///nm inc -531 if tr == 0
        ///tq inc 537 if tq &lt; 9
        ///txm dec 835 if s != -8
        ///xho dec -204 if vv &lt; 6
        ///ipq dec 59 if txm != -835
        ///vv dec -259 if xho &lt;= 210
        ///tq inc 364 if qen != -7
        ///xho inc -198 if xho &lt; 205
        ///afo dec -182 if j == -278
        ///qen inc 774 if ntk == 4
        ///cwp dec -414 if tr &lt; 4
        ///vv dec -696 if ntk == 0
        ///low dec 851 if n == 0
        ///tq inc -132 if t &gt; -10
        ///mux dec 626 if j &gt;= -283
        ///wby dec 759 if vv &gt;= 950
        ///qen inc 853 if j &gt;= -283
        ///qen inc -571 if tr ! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay08 {
            get {
                return ResourceManager.GetString("InputDay08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{{{{&lt;a}!!!aa!!!&gt;ua,a,!&gt;{!&gt;!!!&gt;a&gt;,&lt;!&gt;,!!!!,!!!&quot;!,!a!e}!&gt;!&gt;,&lt;!!oi!!}&gt;},&lt;!!&apos;u&quot;!!!!!&gt;,&lt;e&gt;}},{{&lt;}eaa&apos;&lt;!&gt;},&lt;&lt;&gt;},&lt;}&lt;!},!&gt;},&lt;e&gt;}}},{{{{}}},{{{&lt;,!&gt;,&lt;!!}!&gt;!!!&gt;!!!&gt;!&gt;!&gt;a!!,!!&apos;,&gt;},&lt;e,!!!!!&gt;&lt;&apos;!&lt;,&gt;},{{{&lt;!&lt;!&gt;i&apos;u&quot;&gt;}},&lt;!e!!!&gt;!!eo!!&quot;&quot;&apos;!&gt;,&lt;a!i!!!&gt;!!,,&gt;}}},{{{{{{&lt;o!!&apos;&apos;!!!&gt;!&gt;,&lt;e}a!&gt;},&lt;&gt;}}},{{&lt;aeo!!!&gt;!!!!&lt;!!!!!!!&gt;,&lt;uu!&gt;},&lt;{!!!&gt;&gt;},{&lt;&gt;}}},{{{&lt;},!!&apos;&gt;}},{{&lt;!&quot;}}!!!ooe&apos;!o!!!!&lt;&gt;},{&lt;u!&apos;aoa!!u{!o!&gt;!&gt;},&lt;!!!&gt;&apos;&gt;}},{{{&lt;!&gt;,&lt;!!!&gt;}!!!&gt;u&gt;},&lt;&apos;a,!&gt;,&lt;!{&lt;!!!&gt;e!&gt;!u&gt;},{{{{},&lt;!&gt;e!&quot;&quot;!!&apos;e&quot;&gt;},&lt;{e!!!&gt;!}&apos;}o!&gt;,&lt;,o!&gt;},&lt;!!}!&gt;,&lt;i&gt;},&lt;!&gt;},&lt;!oo&apos;!&gt;},&lt;}}&lt;&apos;o}!&gt;,&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay09 {
            get {
                return ResourceManager.GetString("InputDay09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 129,154,49,198,200,133,97,254,41,6,2,1,255,0,191,108.
        /// </summary>
        internal static string InputDay10 {
            get {
                return ResourceManager.GetString("InputDay10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se,s,s,sw,sw,sw,sw,sw,sw,nw,nw,nw,se,n,nw,nw,nw,n,n,nw,n,n,n,ne,n,ne,ne,nw,se,n,ne,ne,n,ne,ne,ne,sw,ne,ne,n,ne,se,se,ne,ne,s,ne,s,ne,nw,se,ne,ne,ne,se,se,se,se,s,se,se,se,se,nw,se,se,se,se,se,n,s,se,se,se,se,ne,se,s,se,se,s,s,ne,se,se,s,se,nw,nw,nw,ne,sw,s,nw,s,sw,s,nw,s,s,nw,s,s,sw,n,s,s,sw,sw,sw,se,n,ne,ne,s,s,se,sw,n,s,s,sw,sw,sw,sw,s,s,nw,s,s,s,sw,s,se,sw,sw,s,sw,sw,n,sw,s,sw,nw,sw,sw,sw,sw,sw,ne,ne,sw,nw,nw,ne,sw,nw,nw,nw,sw,sw,sw,sw,ne,sw,sw,sw,sw,sw,nw,sw,sw,sw,ne,sw,sw,sw,s,se,nw,nw,nw,nw,sw,n,nw,nw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay11 {
            get {
                return ResourceManager.GetString("InputDay11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 &lt;-&gt; 659, 737
        ///1 &lt;-&gt; 1, 1433
        ///2 &lt;-&gt; 982, 1869
        ///3 &lt;-&gt; 306, 380, 1462, 1827
        ///4 &lt;-&gt; 1076
        ///5 &lt;-&gt; 794, 1451
        ///6 &lt;-&gt; 146, 1055
        ///7 &lt;-&gt; 834, 1557
        ///8 &lt;-&gt; 1333
        ///9 &lt;-&gt; 849, 906, 1863
        ///10 &lt;-&gt; 362, 505
        ///11 &lt;-&gt; 33, 938, 1896
        ///12 &lt;-&gt; 490, 913
        ///13 &lt;-&gt; 189, 690
        ///14 &lt;-&gt; 796
        ///15 &lt;-&gt; 56, 280, 1288, 1721
        ///16 &lt;-&gt; 16
        ///17 &lt;-&gt; 904
        ///18 &lt;-&gt; 150, 1394, 1458
        ///19 &lt;-&gt; 1773
        ///20 &lt;-&gt; 70
        ///21 &lt;-&gt; 993
        ///22 &lt;-&gt; 22
        ///23 &lt;-&gt; 285, 1004
        ///24 &lt;-&gt; 209, 727
        ///25 &lt;-&gt; 614, 1590
        ///26 &lt;-&gt; 113
        ///27 &lt;-&gt; 1321, 1341
        ///28 &lt;-&gt; 351, 730, 1037
        ///29 &lt;-&gt; 29, 1828
        ///30 &lt;-&gt; 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay12 {
            get {
                return ResourceManager.GetString("InputDay12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 3
        ///1: 2
        ///2: 6
        ///4: 4
        ///6: 4
        ///8: 10
        ///10: 6
        ///12: 8
        ///14: 5
        ///16: 6
        ///18: 8
        ///20: 8
        ///22: 12
        ///24: 6
        ///26: 9
        ///28: 8
        ///30: 8
        ///32: 10
        ///34: 12
        ///36: 12
        ///38: 8
        ///40: 12
        ///42: 12
        ///44: 14
        ///46: 12
        ///48: 12
        ///50: 12
        ///52: 12
        ///54: 14
        ///56: 14
        ///58: 14
        ///60: 12
        ///62: 14
        ///64: 14
        ///66: 17
        ///68: 14
        ///72: 18
        ///74: 14
        ///76: 20
        ///78: 14
        ///82: 18
        ///86: 14
        ///90: 18
        ///92: 14.
        /// </summary>
        internal static string InputDay13 {
            get {
                return ResourceManager.GetString("InputDay13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nbysizxe.
        /// </summary>
        internal static string InputDay14 {
            get {
                return ResourceManager.GetString("InputDay14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator A starts with 722
        ///Generator B starts with 354.
        /// </summary>
        internal static string InputDay15 {
            get {
                return ResourceManager.GetString("InputDay15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x5/11,s12,x10/4,pi/d,x11/0,s6,x14/3,pa/b,x6/13,pk/m,x3/9,s12,pg/d,x14/7,pi/b,x13/15,s5,x1/8,s3,x11/6,s6,x9/2,s13,x1/3,pj/a,x13/12,s6,x9/15,s1,x7/0,s1,x11/10,s6,x3/0,s6,x9/8,pl/k,x12/13,pb/n,x15/7,pg/l,x0/11,s12,x12/10,s11,x6/9,po/i,x8/3,pk/l,s2,x14/2,s15,x6/12,pj/p,x7/14,pb/f,x3/15,ph/l,x11/1,s9,pg/o,s9,x8/2,ph/l,s15,x14/0,s1,x13/6,pj/g,x14/7,s7,pi/o,x1/12,pm/a,x13/14,s12,x4/8,pp/c,x13/14,pb/a,x0/7,s4,x5/11,s12,x1/4,s11,x6/10,pi/h,x2/8,s14,x12/3,s12,x11/7,s15,x0/13,pk/a,x11/6,s15,x8/0,s8,x7/5,s10,x9/12,s15, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay16 {
            get {
                return ResourceManager.GetString("InputDay16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 394.
        /// </summary>
        internal static string InputDay17 {
            get {
                return ResourceManager.GetString("InputDay17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set i 31
        ///set a 1
        ///mul p 17
        ///jgz p p
        ///mul a 2
        ///add i -1
        ///jgz i -2
        ///add a -1
        ///set i 127
        ///set p 680
        ///mul p 8505
        ///mod p a
        ///mul p 129749
        ///add p 12345
        ///mod p a
        ///set b p
        ///mod b 10000
        ///snd b
        ///add i -1
        ///jgz i -9
        ///jgz a 3
        ///rcv b
        ///jgz b -1
        ///set f 0
        ///set i 126
        ///rcv a
        ///rcv b
        ///set p a
        ///mul p -1
        ///add p b
        ///jgz p 4
        ///snd a
        ///set a b
        ///jgz 1 3
        ///snd b
        ///set f 1
        ///add i -1
        ///jgz i -11
        ///snd a
        ///jgz f -16
        ///jgz a -19.
        /// </summary>
        internal static string InputDay18 {
            get {
                return ResourceManager.GetString("InputDay18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                                                                                                                              |                           
        ///       +-------+             +---+                                         +-------------+           +-+   +---------+ +---------------------------------------------------------+ +-+     +---+         
        ///       |       |             |   |                                         |             |           | |   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay19 {
            get {
                return ResourceManager.GetString("InputDay19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p=&lt;-3770,-455,1749&gt;, v=&lt;-4,-77,53&gt;, a=&lt;11,7,-9&gt;
        ///p=&lt;1430,195,-903&gt;, v=&lt;-123,60,20&gt;, a=&lt;5,-5,1&gt;
        ///p=&lt;-2964,-3029,2594&gt;, v=&lt;-8,157,7&gt;, a=&lt;9,-3,-8&gt;
        ///p=&lt;-6383,-4277,-3529&gt;, v=&lt;29,70,67&gt;, a=&lt;16,7,5&gt;
        ///p=&lt;3458,4134,-3451&gt;, v=&lt;-12,-132,64&gt;, a=&lt;-9,-2,5&gt;
        ///p=&lt;-702,5382,6208&gt;, v=&lt;-68,-45,-132&gt;, a=&lt;7,-12,-8&gt;
        ///p=&lt;2353,-1261,-747&gt;, v=&lt;-37,8,-40&gt;, a=&lt;-4,3,5&gt;
        ///p=&lt;481,6074,-5911&gt;, v=&lt;-64,-51,159&gt;, a=&lt;3,-9,2&gt;
        ///p=&lt;-3084,-2792,1033&gt;, v=&lt;-29,43,15&gt;, a=&lt;8,3,-3&gt;
        ///p=&lt;-325,1951,-7399&gt;, v=&lt;-86,50,47&gt;, a=&lt;6,-7,12&gt;
        ///p=&lt;4170,-2482,2893&gt;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay20 {
            get {
                return ResourceManager.GetString("InputDay20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../.. =&gt; ..#/#../.#.
        ///#./.. =&gt; #../#../...
        ///##/.. =&gt; ###/#.#/#..
        ///.#/#. =&gt; ###/##./.#.
        ///##/#. =&gt; .../.#./..#
        ///##/## =&gt; ##./#.#/###
        ///.../.../... =&gt; ##../.#../#.#./....
        ///#../.../... =&gt; ..../##.#/...#/##.#
        ///.#./.../... =&gt; ###./####/#.../#..#
        ///##./.../... =&gt; ###./.##./...#/..##
        ///#.#/.../... =&gt; .###/.##./#.../#.##
        ///###/.../... =&gt; ##.#/#..#/#.#./#.##
        ///.#./#../... =&gt; #.#./.###/#.../#.##
        ///##./#../... =&gt; #.../####/#.##/....
        ///..#/#../... =&gt; #.##/..#./...#/...#
        ///#.#/#../... =&gt; #.##/####/.#.#/#.#.
        ///.##/#../... =&gt; #.../ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay21 {
            get {
                return ResourceManager.GetString("InputDay21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .###.#.#####.##.#...#....
        ///..####.##.##.#..#.....#..
        ///.#####.........#####..###
        ///#.#..##..#.###.###.#.####
        ///.##.##..#.###.###...#...#
        ///#.####..#.#.##.##...##.##
        ///..#......#...#...#.#....#
        ///###.#.#.##.#.##.######..#
        ///###..##....#...##....#...
        ///###......#..#..###.#...#.
        ///#.##..####.##..####...##.
        ///###.#.#....######.#.###..
        ///.#.##.##...##.#.#..#...##
        ///######....##..##.######..
        ///##..##.#.####.##.###.#.##
        ///#.###.#.##....#.##..####.
        ///#.#......##..####.###.#..
        ///#..###.###...#..#.#.##...
        ///#######..#.....#######..#        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay22 {
            get {
                return ResourceManager.GetString("InputDay22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay23 {
            get {
                return ResourceManager.GetString("InputDay23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay24 {
            get {
                return ResourceManager.GetString("InputDay24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InputDay25 {
            get {
                return ResourceManager.GetString("InputDay25", resourceCulture);
            }
        }
    }
}
